### ISSUE TITLE
Mobile devices

### ISSUE THREAD

**Issue by buschtoens** [ForbesLindesay-Unmaintained/component-website#10]
![Safari](http://n68.img-up.net/Foto138e.png)

The GitHub logo should be moved left.

I can't explain the right border...

**Comment by ForbesLindesay** [comment]
Yeh, would be nice to get this fixed, I can't say that it's a high priority for me though...I'll accept pull requests though

**Comment by buschtoens** [comment]
Of course it's low prio. But I'll do that. ;)

**Comment by buschtoens** [comment]
Still have to play Sherlock Holmes on the right border. :mag:
