### ISSUE TITLE
End Of Life

### ISSUE THREAD

**Issue by ForbesLindesay** [ForbesLindesay-Unmaintained/component-website#19]
I just want to let anyone who's still using this site know that it's reaching its end of life.  I will be taking `component.jit.su` down on 2013-05-10 ahead of nodejitsu's pricing increase.  Now that http://component.io is live it shouldn't be needed.  The only functionality that's unique to this website is serving up the builds.  I think someone should sort out adding that functionality to https://github.com/component/component.io as soon as possible but unfortunately I don't currently have time to do it.

I should add that it was always my intention to make `component.jit.su` a temporary solution, it's just being pushed by the price increase.

**Comment by buschtoens** [comment]
Thanks for all your work. ;)
