### ISSUE TITLE
Update source code

### ISSUE THREAD

**Issue by buschtoens** [ForbesLindesay-Unmaintained/component-website#2]
This doesn't seem to be the up to date code. Could you please push?

**Comment by ForbesLindesay** [comment]
It is up to date.  What seems out of date?  Maybe I've added something to git-ignore un-intentionaly?

**Comment by buschtoens** [comment]
Whups, you're right. My fork just didn't update properly.
Sorry.

**Comment by ForbesLindesay** [comment]
cool, no problem
