### ISSUE TITLE
Branding & Continuous Integration/Testing of components

### ISSUE THREAD

**Issue by timoxley** [ForbesLindesay-Unmaintained/component-website#4]
I'd just make the site white and black or drop some twitter bootstrap on it… black and white is far more in keeping with all the 'component' branding thus far.

**Comment by ForbesLindesay** [comment]
I was deliberately attempting to avoid bootstrap (my natural go to for this sort of thing) and hand code the css because that seemed more in keeping with the component ethos.  I think we should keep the css file hand-coded and relatively short, but I'm happy to have it be black and white.

Since that seems more in-keeping with the component brand, I'll happily accept a pull-request to remove the colour.

**Comment by ForbesLindesay** [comment]
I do think we should continue to hand-code the CSS though, rather than use things like bootstrap.

**Comment by ForbesLindesay** [comment]
What do you think of the new version, with all colour removed?  Comments, thoughts, suggestions, better/worse? @silvinci @visionmedia

**Comment by timoxley** [comment]
Looks a lot better. Like… 1000% better. 

The links/component names are a little hard to read.

**Comment by ForbesLindesay** [comment]
Hmm, yeh, perhaps they should still be a different colour...

**Comment by buschtoens** [comment]
Looks better. ;)

But imho we should have _one_ strong branding color.

**Comment by ForbesLindesay** [comment]
If we did, we'd have a nice colour to make links ;)

**Comment by tj** [comment]
I've got a couple things in mind to try, just haven't got there yet. I'll upload the vectors to component/component soonish too so everyone can get at them

**Comment by tj** [comment]
k added the heavy / light vectors https://github.com/component/component/downloads

**Comment by tj** [comment]
I really like the auto-TOC stuff haha, github reallyyyyyy needs to do that

**Comment by ForbesLindesay** [comment]
Yeh, that was 80% of the reason for wanting to re-produce the readme files.  If you want to replace the home page with the appropriate vector image that would be awesome. I'll give @visionmedia commit access too (and push to production fairly regularly so we can iterate quickly).  I really want to start indicating which projects have associated travis tests on the listing pages as I think that should be pretty high up on people's list of priorities when choosing components (it certainly is on mine).

**Comment by tj** [comment]
travis doesn't have client-side support do they? Once I get mocha-ci going we can have per-browser test info for the badges

**Comment by ForbesLindesay** [comment]
You can do headless browser testing using phantomJS, and with a little bit more work you can use xvfb for gui testing (although I've not tried that), so most things should be testable.  See http://about.travis-ci.org/docs/user/gui-and-headless-browsers/ for more info.  Also https://github.com/tricknotes/mocha-ci-driver looks promising.

Where possible I tend to try and fake out the necessary APIs and then just test in node though.  e.g. https://github.com/microjs/DOMinate/blob/master/test/document-mock.js  The nice thing is that you can just make your test script in package.json be `component-install && component-build -s b && mocha`

What's mocha-ci sounds intriguing and awesome though...I look forward to seeing what you come up with.

**Comment by ForbesLindesay** [comment]
I've made phantomjs work for a real component.  https://github.com/microjs/path/commit/8ca7a8bfbf59df60095f4d3d643708fbfdfc9e1d shows all I had to change to make my mocha tests work from the command line using `npm test` and in travis-ci.  The only other thing I had do do was install [phantomjs](http://phantomjs.org/download.html) which has builds for windows etc. It really is awesome stuff.

**Comment by tj** [comment]
I've use mocha-phantomjs, but that's still not x-browser testing

**Comment by ForbesLindesay** [comment]
Yeh, x-browser CI would be awesome, but I do think we should be encouraging as many modules as possible to support automated tests with some sort of CI right now, and move to x-browser testing once someone's sorted out how we're going to do that.

**Comment by ForbesLindesay** [comment]
Closing in favour of #5.  Feel free to open a new issue with any suggested changes to colour scheme/branding once that's worked out.
