### ISSUE TITLE
Build statuses/What else should go on the home screen

### ISSUE THREAD

**Issue by ForbesLindesay** [ForbesLindesay-Unmaintained/component-website#5]
We now have build status badges from travis displaying on the home screen (where they can be found in the readme).  What do people think of these, how can they be improved?  Once we've got cross browser testing in place from @visionmedia I expect that to replace travis for most modules, but I really like this in the interim.

What else should go on the listing pages for each module?  If we encourage people to add a 'licence' property to their component.json files we could easily enough include that in the display...

**Comment by tj** [comment]
the problem with travis CI for this sort of thing is that it doesn't really do anything, single-env CI is really odd IMO, because devs should be running tests pre-commit anyway. `.license` is definitely a good one to have, the bot added it to most but I didn't let it run all the way through yet

**Comment by ForbesLindesay** [comment]
I think the key advantage is that it represents a clean environment to run tests, and it represents tests that will always be run for **every** commit, even if a dev gets lazy.  The other nice thing is that it tests on pull requests etc.  I guess my feeling is mostly that there should be a system of fully automated tests wherever possible, and it would be nice to indicate that they exist on the home page (I'm not that interested in whether they're currently passing or failing, failing tests probably just indicates active development).

I'll add licenses on then, it would be good to let the bot run the rest of the way through :smile:

**Comment by buschtoens** [comment]
Stars should be on there too.

**Comment by tj** [comment]
later it may be nice to define theme relationships in component.json as well, so it's easy to link themes to any given component, vs people sending pull-requests for github readmes. tough call though I would still like them in readmes as well

**Comment by buschtoens** [comment]
Linking the themes in the readmes then sounds like a job for [component/bot](https://github.com/component/bot). Automation is badass. #16
